"use client";
import {useState} from "react";
const products=[["01","LIGHTING","LED lights, panels & bulbs"],["02","SWITCHGEAR","Switches, sockets & MCBs"],["03","WIRES & CABLES","Everyday wiring essentials"],["04","ELECTRICAL ACCESSORIES","Reliable electrical goods"]];
const phone="+91 98270 72060";
export default function Home(){const [open,setOpen]=useState(false);return <main>
<header className="nav"><a className="brand" href="#home"><span className="logo">A</span><span><b>AMIT</b><small>ELECTRICALS</small></span></a><button className="menu" onClick={()=>setOpen(!open)} aria-label="Menu">☰</button><nav className={open?"links open":"links"}><a href="#home" onClick={()=>setOpen(false)}>Home</a><a href="#products" onClick={()=>setOpen(false)}>Products</a><a href="#about" onClick={()=>setOpen(false)}>About</a><a href="#contact" onClick={()=>setOpen(false)}>Contact</a></nav><a className="call" href="tel:+919827072060">Call now ↗</a></header>
<section id="home" className="hero"><div className="grid"/><div className="copy"><div className="eyebrow"><span/> KALAKHET • MANDSAUR</div><h1>LIGHT UP<br/><em>YOUR WORLD.</em></h1><p>Trusted electrical goods, practical solutions and quality products for homes, shops and businesses.</p><div className="buttons"><a className="primary" href="#products">Explore products <b>→</b></a><a className="ghost" href="#contact">Visit our store</a></div><div className="mini"><span>●</span> Open Mon–Sat · 10:00 AM–9:00 PM</div></div><div className="scene"><div className="halo h1"/><div className="halo h2"/><div className="lamp"><div className="shade"/><div className="bulb"><i/></div><div className="stem"/></div><div className="badge one"><small>QUALITY</small><b>TRUSTED</b><span>✦</span></div><div className="badge two"><small>LOCAL</small><b>MANDSAUR</b><span>✓</span></div></div></section>
<section className="trust"><div><strong>23+</strong><span>Years in business*</span></div><div><strong>4.6★</strong><span>Customer rating</span></div><div><strong>08:30 PM</strong><span>Closing time</span></div><div><strong>UPI</strong><span>Easy payments</span></div></section>
<section id="products" className="section"><div className="sectionTitle"><div><p className="eyebrow">WHAT WE STOCK</p><h2>Electrical essentials.<br/><em>Made simple.</em></h2></div><p>Find everyday electrical goods and accessories with a focus on dependable brands and helpful local service.</p></div><div className="cards">{products.map(([n,t,d])=><article className="product" key={n}><span className="num">{n}</span><div className="productIcon">{n==="01"?"◉":n==="02"?"⌁":n==="03"?"≋":"◇"}</div><h3>{t}</h3><p>{d}</p><a href="#contact">Ask about this →</a></article>)}</div></section>
<section id="about" className="about"><div className="aboutVisual"><div className="cube"><span>AMIT</span><b>ELECTRICALS</b></div></div><div><p className="eyebrow">ABOUT THE STORE</p><h2>Your local electrical<br/><em>partner in Mandsaur.</em></h2><p>Amit Electricals is an electrical supply store at Road Number 3, Kalakhet, Mandsaur. The public business listing identifies it as a long-running local electrical shop, serving customers with electrical goods and related products.</p><div className="facts"><div><b>2003</b><span>Listed establishment year*</span></div><div><b>458002</b><span>Mandsaur PIN</span></div></div></div></section>
<section id="contact" className="contact"><div><p className="eyebrow">COME SAY HELLO</p><h2>Need electrical<br/><em>supplies?</em></h2><p>Call us or visit the store on Road Number 3, Kalakhet, Mandsaur.</p><div className="contactButtons"><a className="primary" href="tel:+919827072060">Call {phone} <b>→</b></a><a className="ghost light" href="https://www.google.com/maps/search/?api=1&query=Amit+Electricals+Rd+Number+3+Kalakhet+Mandsaur+Madhya+Pradesh+458002" target="_blank">Open Maps ↗</a></div></div><div className="address"><span>STORE</span><strong>Amit Electricals</strong><p>Rd Number 3, Kalakhet<br/>Mandsaur, Madhya Pradesh 458002</p><hr/><span>HOURS</span><p>Monday – Saturday<br/><b>10:00 AM – 9:00 PM</b><br/><small>Sunday · Closed</small></p></div></section>
<footer><div className="brand footerBrand"><span className="logo">A</span><span><b>AMIT</b><small>ELECTRICALS</small></span></div><p>Electrical goods • Kalakhet • Mandsaur</p><a href="tel:+919827072060">{phone}</a><span>© 2026 Amit Electricals</span></footer>
</main>}